forge "https://forgeapi.puppetlabs.com"

mod "attachmentgenie/locales"
mod "saz/timezone"
mod "maestrodev/wget"
mod "puppetlabs/apt"
mod "puppetlabs/stdlib"
mod "computology/packagecloud"

mod "jfryman/nginx"
mod "nodes/php"
